### ISSUE TITLE
Protect from mistakes by defaulting to file level :eval never setting,

### ISSUE THREAD

**Issue by thomasf** [lujun9972/code-library#5]
To avoid unhappy accidents.
 I don.t think this needs to be optional, right?

IIRC this prohibits org-mode from evaluating source blocks when exporting regardless of other settings. If it doesn't that needs to be ensured as well.

**Comment by thomasf** [comment]
Or maybe it's better to just add something that inserts this  (probably from a defcustom) into all new .org files.

```
#+PROPERTY: eval never
```

**Comment by thomasf** [comment]
Then it becomes up to the end user to make things more risky.

I'm already slightly scared about what would happen if a couple of my code library org files were to to be executed by mistake.

**Comment by lujun9972** [comment]
I'm sorry, I don't get it. 
what's the :output argument's meaning? why should add this argument?

**Comment by thomasf** [comment]
when exporting an .org file to a .html file the source code will be exported instead of the output of the source block. Depending on org mode settings org-mode can start to evaluate all source blocks while exporting which for random collections of code can be very dangerous.

**Comment by thomasf** [comment]
EDIT.. sorry the keyword is `:exports`

http://orgmode.org/manual/exports.html#exports

In any case the org mode file level header property keywords probably is the best place to do this.. Also adding `eval never` protects inexperienced org users from making mistakes.

http://orgmode.org/manual/eval.html

**Comment by lujun9972** [comment]
en.... It seems reasonable.

**Comment by lujun9972** [comment]
I have to read the manual first

**Comment by thomasf** [comment]
For myself I have `org-confirm-babel-evaluate` set to `nil` because I like to think that all my .org files has sensible defaults depending on use case. I would not expect an auto gathered file to allow random evaluation too easily.

**Comment by lujun9972** [comment]
So, The only thing I have to do is put ":exports code :eval  no-export" behind the ":tangle" part right?

**Comment by thomasf** [comment]
Just put `#+PROPERTY: eval never` at the top of each empty `.org` file instead. 

A `defcustom` looking something like this is probably good:

``` el
(defcustom code-library-org-file-header "#+PROPERTY: eval never

"
"Header to be inserted in org-files.

This is automatically done by code-library before inserting
snippets into empty or new .org files.")
```

Users can then choose to use a less restrictive variants like `:eval no-export` by customizing.

`:eval never` will block any attempt by org mode to evaluate the block so we don't need to care about the `:exports` argument.

**Comment by thomasf** [comment]
The file header `defcustom` also allows me to customize personal settings as well..
I want to have something like this in my files but it should not be the default value:

``` el
(setq code-library-org-file-header "#+FILETAGS: personal code
#+CATEGORY: clib
#+EXPORT_EXCLUDE_TAGS: noexport
#+PROPERTY: exports code
#+PROPERTY: eval never
#+PROPERTY: no-expand
#+OPTIONS: toc:2 num:nil ^:nil
#+INFOJS_OPT: view:info toc:t ltoc:t mouse:underline buttons:0 path:http://thomasf.github.com/solarized-css/org-info.min.js
#+HTML_HEAD:  <link rel="stylesheet" type="text/css" href="http://thomasf.github.com/solarized-css/solarized-light.min.css" />
#+OPTIONS:   H:4 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:nil skip:nil d:t tags:not-in-toc

")
```

The header above produces this export  : 
http://datamaskinen.medeltiden.org/downloads/osinstall/osinstall.html
